payment/cart/urls.py
from django.urls import re_path
from . import views


urlpatterns = [
    re_path(r'^$',
            views.cart_detail,
            name='cart_detail'),
    re_path(r'^add/(?P<item_id>\d+)/$',
            views.cart_add,
            name='cart_add'),
    re_path(r'^remove/(?P<item_id>\d+)/$',
            views.cart_remove,
            name='cart_remove'),
]

payment/goods/urls.py
from django.urls import path

from .views import (
                    create_checkout_cart,
                    create_checkout_item, ProductListView,
                    ProductCreateView, ProductDetailView,
                    PaymentSuccessView, PaymentFailedView,
                    OrderHistoryListView)

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('item/<int:id>/', ProductDetailView.as_view(), name='item'),
    path('success/', PaymentSuccessView.as_view(), name='success'),
    path('failed/', PaymentFailedView.as_view(), name='failed'),
    path('history/', OrderHistoryListView.as_view(), name='history'),

    path('buy/<int:id>/', create_checkout_item,
         name='buy'),
    path('buy/', create_checkout_cart, name='buy-cart')
]

payment/payment/urls.py
from django.contrib import admin
from django.urls import include, path, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('', include(('goods.urls', 'goods'), namespace='goods'))
]

payment/goods/models.py
from django.db import models
from django.core import validators


class Item(models.Model):
    name = models.CharField(max_length=180)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField(validators=[
        validators.MinValueValidator(50),
        validators.MaxValueValidator(100000)
    ])


class Order(models.Model):
    items = models.ManyToManyField(Item,
                                   related_name='orders')
    customer_email = models.EmailField()
    amount = models.IntegerField()
    has_paid = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)

payment/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False, widget=forms.HiddenInput)

payment/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.conf import settings

from goods.models import Item
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, item_id):
    cart = Cart(request)
    product = get_object_or_404(Item, id=item_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, item_id):
    cart = Cart(request)
    product = get_object_or_404(Item, id=item_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    template_name = 'cart/detail.html'
    stripe = settings.STRIPE_PUBLISHABLE_KEY
    cart = Cart(request)
    return render(request, template_name, {'cart': cart,
                                           'stripe_publishable_key': stripe})

payment/goods/views.py
from django.views.decorators.http import require_POST
from django.http.response import (HttpResponseNotFound,
                                  JsonResponse)
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, TemplateView
import stripe
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import json

from cart.cart import Cart
from .models import Item, Order
from cart.forms import CartAddProductForm


class ProductListView(ListView):
    model = Item
    template_name = 'payments/product_list.html'
    context_object_name = 'product_list'


@method_decorator(staff_member_required, name='dispatch')
class ProductCreateView(CreateView):
    model = Item
    fields = '__all__'
    template_name = 'payments/product_create.html'
    success_url = reverse_lazy('goods:home')


class ProductDetailView(DetailView):
    model = Item
    template_name = 'payments/product_detail.html'
    pk_url_kwarg = 'id'

    # def product_detail(self, request, id):
    #     item = get_object_or_404(Item,
    #                              pk=id,
    #                              available=True)
    #     cart_product_form = CartAddProductForm()
    #     return render(request, self.template_name,
    #                   {'item': item,
    #                    'cart_product_form': cart_product_form})

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['stripe_publishable_key'] = settings.STRIPE_PUBLISHABLE_KEY
        context['cart_product_form'] = CartAddProductForm()
        return context


@csrf_exempt
def create_checkout_item(request, id):
    item = get_object_or_404(Item, pk=id)
    cart = [
        {
            'product': item,
            'price': item.price,
            'quantity': 1,
            'total_price': item.price,
        }
    ]
    return create_checkout_session(request, cart)


def create_checkout_session(request, cart):
    stripe.api_key = settings.STRIPE_SECRET_KEY
    request_data = json.loads(request.body)
    order = Order()
    order.customer_email = request_data['email']
    order.amount = sum(map(lambda item: item['total_price'] * 100, cart))
    order.save()
    order.items.add(*list(map(lambda x: x['product'], cart)))

    checkout_session = stripe.checkout.Session.create(
        customer_email=request_data['email'],
        payment_method_types=['card'],
        line_items=[
            {
                'price_data': {
                    'currency': 'usd',
                    'product_data': {
                        'name': item['product'].name,
                        },
                    'unit_amount': int(item['price'] * 100),
                    },
                'quantity': item['quantity'],
            } for item in cart
        ],
        mode='payment',
        success_url=request.build_absolute_uri(
            reverse('goods:success')
        ) + f"?order_id={order.id}",
        cancel_url=request.build_absolute_uri(reverse('goods:failed')),
    )

    return JsonResponse({'sessionId': checkout_session.id})


@csrf_exempt
@require_POST
def create_checkout_cart(request):
    cart = Cart(request)
    return create_checkout_session(request,
                                   cart)


class PaymentSuccessView(TemplateView):
    template_name = 'payments/payment_success.html'

    def get(self, request, *args, **kwargs):
        order_id = request.GET.get('order_id')
        if order_id is None:
            return HttpResponseNotFound()

        stripe.api_key = settings.STRIPE_SECRET_KEY

        order = get_object_or_404(Order,
                                  pk=order_id)
        order.has_paid = True
        order.save()
        return render(request, self.template_name)


class PaymentFailedView(TemplateView):
    template_name = 'payments/payment_failed.html'


@method_decorator(staff_member_required, name='dispatch')
class OrderHistoryListView(ListView):
    model = Order
    template_name = 'payments/order_history.html'

payment/goods/templates/cart/detail.html
{% extends "payments/base.html" %}
{% load static %}
{% block title %}Your shopping cart{% endblock %}
{% block content %}
    <h1 class="text-center">Your shopping cart</h1>
    <div class="container">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Remove</th>
                    <th>Unit price</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                    {% with product=item.product %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img class="card-img-top"
                                         src="https://dummyimage.com/50x50.jpg?text={{ product.name }}"
                                         alt="">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>{{ item.quantity }}</td>
                            <td>
                                <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                            </td>
                            <td class="num">${{ item.price }}</td>
                            <td class="num">${{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr class="total">
                    <td>Total</td>
                    <td colspan="4"></td>
                    <td class="num" id="totalprice">${{ cart.get_total_price }}</td>
                </tr>
            </tbody>
        </table>
        <p class="text-right">
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email"
                       name="email"
                       id="email"
                       class="form-control"
                       placeholder="Email">
                <small>Please enter your email address</small>
            </div>
            <a href="{% url "goods:home" %}" class="btn btn-success ml-auto">Continue shopping</a>
            <button class="btn btn-success ml-auto" id="checkout-button">Checkout</button>
        </p>
    </div>
    <script src="https://js.stripe.com/v3/"></script>
    <script type="text/javascript">
    var stripe = Stripe('{{ stripe_publishable_key }}');
    var checkoutButton = document.getElementById('checkout-button');

    checkoutButton.addEventListener('click', function () {
        var totalprice = document.getElementById('totalprice').innerText;
        if (totalprice == '$0') {
            alert("Your cart is empty");
            return;
        }
        var email = document.getElementById('email').value;
        if (email.length == 0) {
            alert("Please enter your email address.");
            return;
        }
        

        
        fetch("{% url 'goods:buy-cart' %}", {
            method: 'POST',
            body: JSON.stringify(
                { email: email }
            )
        })
            .then(function (response) {
                return response.json();
            })
            .then(function (session) {
                return stripe.redirectToCheckout({ sessionId: session.sessionId });
            })
            .then(function (result) {
                if (result.error) {
                    alert(result.error.message);
                }
            })
            .catch(function (error) {
                console.error('Error:', error);
            });
    });
    </script>
{% endblock %}

payment/goods/templates/payments/base.html
<!doctype html>
<html lang="en">
    <head>
        <title>Django Payments App</title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
              crossorigin="anonymous">
    </head>
    <body>
        {% include 'payments/navbar.html' %}
        {% block content %}
        {% endblock content %}
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    </body>
</html>

payment/goods/templates/payments/navbar.html
{% load static %}
<nav class="navbar navbar-expand-sm navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'goods:home' %}">BettleShop</a>
    <button class="navbar-toggler d-lg-none"
            type="button"
            data-toggle="collapse"
            data-target="#collapsibleNavId"
            aria-controls="collapsibleNavId"
            aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'goods:home' %}">Home</a>
            </li>
            {% if request.user.is_staff %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'goods:create' %}">New Product</a>
                </li>
            {% endif %}
            {% if request.user.is_staff %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'goods:history' %}">Order History</a>
                </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cart:cart_detail' %}">Cart</a>
            </li>
        </ul>
    </div>
</nav>

payment/goods/templates/payments/order_history.html
{% extends 'payments/base.html' %}
{% block content %}
    <h1 class="text-center">Order History</h1>
    <div class="container">
        {% if object_list %}
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Customer Email</th>
                        <th>Amount</th>
                        <th>Status</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in object_list %}
                        <tr>
                            <td>
                                {% for item in i.items.all %}
                                    {% if not forloop.last %}
                                        {{ item.name }},
                                    {% else %}
                                        {{ item.name }}
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td>{{ i.customer_email }}</td>
                            <td>{{ i.amount }}</td>
                            <td>
                                {% if i.has_paid %}
                                    <b class="text-success">Success</b>
                                {% else %}
                                    <b class="text-danger">Failed</b>
                                {% endif %}
                            </td>
                            <td>{{ i.created_on }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="alert alert-info">Payment history is empty.</div>
        {% endif %}
    </div>
{% endblock content %}

payment/goods/templates/payments/payment_failed.html
{% extends 'payments/base.html' %}
{% block content %}
    <div class="container">
        <div class="jumbotron text-center mt-5">
            <h1 class="text-danger">Payment Failed</h1>
            <p>
                We received your order. You can now close this window or use the
                link below to visit
                <a href="{% url 'goods:home' %}">home page</a>.
            </p>
        </div>
    </div>
{% endblock content %}

payment/goods/templates/payments/payment_success.html
{% extends 'payments/base.html' %}
{% block content %}
    <div class="container">
        <div class="jumbotron text-center mt-5">
            <h1 class="text-success">Payment Success</h1>
            <p>
                We received your order. You can now close this window or use the
                link below to visit
                <a href="{% url 'goods:home' %}">home page</a>.
            </p>
        </div>
    </div>
{% endblock content %}

payment/goods/templates/payments/product_create.html
{% extends 'payments/base.html' %}
{% block content %}
    <h1 class="text-center">Create Product</h1>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                <form method="post">
                    {{ form.as_p }}
                    {% csrf_token %}
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
    document.querySelectorAll('input, textarea').forEach(e => {
        e.classList.add('form-control');
    })
    </script>
{% endblock content %}

payment/goods/templates/payments/product_detail.html
{% extends 'payments/base.html' %}
{% block content %}
    <h1 class="text-center">Product Detail</h1>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h2>Product Detail</h2>
            </div>
            <div class="card-body">
                <div class="container row">
                    <div class="col-md-2">
                        <img src="https://dummyimage.com/150x150.gif?text={{ object.name }}"
                             alt="">
                    </div>
                    <div class="col-md-10">
                        <h1>Name: {{ object.name }}</h1>
                        <p>Description: {{ object.description }}</p>
                        <p>Price: {{ object.price }}$</p>
                        <div class="form-group">
                            <label for="email">Email:</label>
                            <input type="email"
                                   name="email"
                                   id="email"
                                   class="form-control"
                                   placeholder="Email">
                            <small>Please enter your email address</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer d-flex">
                <form action="{% url "cart:cart_add" item.id %}" method="post">
                    {{ cart_product_form }}
                    {% csrf_token %}
                    <input class="btn btn-success ml-auto" type="submit" value="Add to cart">
                </form>
                <button class="btn btn-success ml-auto" id="checkout-button">Checkout</button>
            </div>
        </div>
    </div>
    <script src="https://js.stripe.com/v3/"></script>
    <script type="text/javascript">
    var stripe = Stripe('{{ stripe_publishable_key }}');
    var checkoutButton = document.getElementById('checkout-button');

    checkoutButton.addEventListener('click', function () {

        var email = document.getElementById('email').value;
        if (email.length == 0) {
            alert("Please enter your email address.");
            return;
        }

        
        fetch("{% url 'goods:buy' id=object.id %}", {
            method: 'POST',
            body: JSON.stringify(
                { email: email }
            )
        })
            .then(function (response) {
                return response.json();
            })
            .then(function (session) {
                return stripe.redirectToCheckout({ sessionId: session.sessionId });
            })
            .then(function (result) {
                if (result.error) {
                    alert(result.error.message);
                }
            })
            .catch(function (error) {
                console.error('Error:', error);
            });
    });
    </script>
{% endblock content %}

payment/goods/templates/payments/product_list.html
{% extends 'payments/base.html' %}
{% block content %}
    <h1 class="text-center">Product List</h1>
    <div class="container">
        {% if product_list %}
            <div class="row">
                {% for p in product_list %}
                    <div class="col-sm-4">
                        <div class="card">
                            <img class="card-img-top"
                                 src="https://dummyimage.com/200x150.jpg?text={{ p.name }}"
                                 alt="">
                            <div class="card-body">
                                <h4 class="card-title">{{ p.name }}</h4>
                                <p class="card-text">{{ p.description }}</p>
                            </div>
                            <div class="card-footer d-flex">
                                <p style="margin: auto 0" class="card-text">{{ p.price }}$</p>
                                <a href="{% url 'goods:item' id=p.id %}" class="btn btn-success ml-auto">View</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="alert alert-info text-center mt-5">The product list is empty. Please add some products first.</div>
        {% endif %}
    </div>
{% endblock content %}